### ISSUE TITLE
BUG: Normal map colorspace could not be set

### ISSUE THREAD

**Issue by Az-qianchen** [KirilStrezikozin/BakeMaster-Blender-Addon#27]
**This bug report is:**

- [Code Execution Error: bpy_struct: item.attr = val: enum "Non-Color" not found in ('Linear', 'sRGB')]

**Describe the bug**

The same file can bake normal maps in Blender 3.3, but there is an error in 3.4. Other types of maps can be baked.
I encountered the same error when using the tool below.
https://github.com/jayanam/jbake-tools

**Screenshots**
![tmpC80A](https://user-images.githubusercontent.com/52212525/227427878-7910d301-ae00-4936-9715-b24e8d0605aa.png)

**Desktop (please complete the following information):**
 - OS [e.g. Windows]
 - OS Version [e.g. Windows 11]
 - Blender Version [e.g. Blender 3.4.0]
 - BakeMaster Version [e.g. 2.0]

**Comment by KirilStrezikozin** [comment]
@Az-qianchen thanks for reaching out,
can you provide some more information, please, for me to quickly reproduce the error:

- Screenshot of Normal map settings
- Screenshot of Bake Output settings (especially what `Create Material` property is set to)

If you uncheck `Create Material` (if it was checked), does the issue appear?

**Comment by Az-qianchen** [comment]
![tmp1CD6](https://user-images.githubusercontent.com/52212525/227434287-ed0fe69a-8b82-48ac-a58d-a8b15cc4e219.png)
These are my settings. I selected Create Material, but the problem still exists.

**Comment by Az-qianchen** [comment]
> @Az-qianchen感谢您的联系， 不能提供更多信息，以方便我快速重现错误：
> 
> * 法线贴图设置的屏幕截图
> * Bake Output 设置的屏幕截图（尤其`Create Material`是设置的属性）
> 
> 如果取消消选中`Create Material`（如果已经选中），问题是否出现？

![tmp1CD6](https://user-images.githubusercontent.com/52212525/227434287-ed0fe69a-8b82-48ac-a58d-a8b15cc4e219.png)
 These are my settings. I selected Create Material, but the problem still exists.

**Comment by KirilStrezikozin** [comment]
@Az-qianchen I struggle to replicate the error. Played around the setup and all settings but I always get Normal map baked no matter what.
Is the `Output filepath` empty in your Bake output?
If you remove all objects from bakemaster, and then add again (with normal map and all settings as is), will the error appear?

**Comment by Az-qianchen** [comment]
This is my action in Blender 3.3
![tmpB39C](https://user-images.githubusercontent.com/52212525/227697259-4cbc144f-9235-4476-aad3-182d748a1c60.png)
I got the result

This is my action in Blender 3.4
![tmp268B](https://user-images.githubusercontent.com/52212525/227697284-7b45c520-4df8-430d-8cd3-0521819eef33.png)
Is error

I  changed  computer but the problem remained
I try to do a minimum of setup，I feel very strange

**Comment by Az-qianchen** [comment]
> 这是我在 Blender 3.3 ![tmpB39C](https://user-images.githubusercontent.com/52212525/227697259-4cbc144f-9235-4476-aad3-182d748a1c60.png) 中的操作，我得到了结果
> 
> 这是我在搅拌机 3.4 ![TMP268B](https://user-images.githubusercontent.com/52212525/227697284-7b45c520-4df8-430d-8cd3-0521819eef33.png) 中的操作是错误的
> 
> 我换了电脑，但问题仍然存在

This is my action in Blender 3.3 tmpB39C I got the result This is my action in Blender 3.4 tmp268B Is error I changed computer but the problem remained I try to do a minimum of setup，I feel very strange

**Comment by Az-qianchen** [comment]
> 我努力复制错误。围绕设置和所有设置进行了游戏，但无论如何我总是得到法线贴图烘焙。烘焙输出中的空吗？如果从烘焙大师中删除所有对象，然后再次添加（使用法线贴图和所有设置），是否会出现错误？`Output filepath`

This is my action in Blender 3.3,I got the result
![tmpBA68](https://user-images.githubusercontent.com/52212525/227697656-c5b09ae9-aec7-4017-adee-9534065efdfa.png)

This is my action in Blender 3.4,is error
![tmpDED9](https://user-images.githubusercontent.com/52212525/227697665-f8d92a8a-e4c6-4899-b222-d2b55f58bf9b.png)

I changed computer but the problem remained
I try to do a minimum of setup，I feel very strange

**Comment by KirilStrezikozin** [comment]
Hi, @Az-qianchen. I couldn't reproduce the bug but I added a little check regarding the error so it shouldn't appear any more.

For `2.0.2` release:
- ProbablyFix: #27 ([`dev-366f062`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/commit/366f0629e4050a861c9b57b40732cf655a9a52da))

**Comment by KirilStrezikozin** [comment]
🚩 @Az-qianchen release with this issue most likely fixed is going to be published tonight. Since this conversation will stay alive, if you appear to have any questions or further feedback, I'll be here for you.

Thanks for the report.

see ya baking 🍞
