### ISSUE TITLE
BUG: When baking the high model to the low model, the metal material part cannot be baked to the albedom and metalness

### ISSUE THREAD

**Issue by Maiev-42** [KirilStrezikozin/BakeMaster-Blender-Addon#29]
blender3.4 and blender 3.5

![image](https://user-images.githubusercontent.com/41062473/232720113-af9c0348-c2ee-4471-b858-46f8e07baef7.png)

thanks!

(edited by @KirilStrezikozin)
**TODO:**
- [x] https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/issues/29#issuecomment-1525505868
- [x] Testing

**Comment by KirilStrezikozin** [comment]
Hi, @chen649285912, can you send here screenshots of Suzanne's material and the settings in BakeMaster? I haven't run into this issue before.

**Comment by Maiev-42** [comment]
[test.zip](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/files/11267914/test.zip)


This zip file includes the blend file, screenshots of the settings, and baked textures. Hope  you can solve the problem. Thank you very much!

**Comment by KirilStrezikozin** [comment]
@chen649285912 I'm able to replicate the error. Seems to appear when baking Albedo, Opacity, and Metalness (as you mentioned) from Highpoly.

**Comment by KirilStrezikozin** [comment]
Note for me:
the error is connected with calling `bake_prepare_map(...)` in [`dev/bake_operator`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/blob/376adb1ceeaa32499ad66c64a788c9a752a1fb2d/operator_bake.py#L3735)

**Comment by KirilStrezikozin** [comment]
Note for me:
`bake_object_materials_handle_replug(...)` in [`dev/bake_operator`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/blob/376adb1ceeaa32499ad66c64a788c9a752a1fb2d/operator_bake.py#L2769) is called with passing `source_object` only.

**TODO:**

- [x] add `bake_object_materials_handle_replug(...)` calls and pass `source_highpoly`.
      Calls in:
     1.  `bake_prepare_map(...)`;
     2. `bake_map_restore_mats_replug(...)` (called in `bake_operate_next_object(...)`, `bake_map_get_data(...)`).

**Comment by KirilStrezikozin** [comment]
First fix trial:
(Correctly baked AlbedoM, Metalness, Opacity, AlbedoS, Specular)
![image](https://user-images.githubusercontent.com/77115208/234931258-d4d9a5cb-250b-4620-979b-0f05ae033063.png)
![image](https://user-images.githubusercontent.com/77115208/234931301-c8e93605-98d2-450b-bea4-ba43cd327bfc.png)
![image](https://user-images.githubusercontent.com/77115208/234931339-425d70e4-4941-4950-b39d-78b9e5e8e8ce.png)
![image](https://user-images.githubusercontent.com/77115208/234932759-ab0f4450-4ae2-42e8-a91a-0d0a048da989.png)
![image](https://user-images.githubusercontent.com/77115208/234932812-72d49938-7346-4bcc-9d8a-f494236e388d.png)

**Comment by KirilStrezikozin** [comment]
testing went successful.

**Comment by KirilStrezikozin** [comment]
@chen649285912, `2.0.2` release will be published shortly with the following bug fixes:
- #29 ([`dev-e8f818d`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/commit/e8f818d031b7aaad51ee16f1f89b093b8bc2b4f4), [`dev-257a293`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/commit/257a2936c4203016674f18b60ab011dea6131039))
- ID Maps weren't baked if Object had NoneType Materials ([`dev-a1a4836`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/commit/a1a4836aa42eae83b6173df147ae63545dff5416))
- If bake took more than a minute, "Bake completed in ..." didn't show correct time the bake took ([`dev-de81454`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon-Dev/commit/de81454994b1dd73b59fb1167cf0f76bf0011451))

**Comment by KirilStrezikozin** [comment]
🚩 @chen649285912 release with this issue resolved is going to be published tonight.
I'm closing this issue, but if you have anything to say, don't hesitate to.

Thank you for submitting the bug report. That's a nice and helpful way to contribute to BakeMaster 😄

see ya baking 🍞

**Comment by Maiev-42** [comment]
Thank you for helping solve this problem! I also purchased Full version: single user on BlenderMarket, which will help me with batch baking.
