### ISSUE TITLE
REQUEST: Bulk option to edit multiple meshes at once!

### ISSUE THREAD

**Issue by TheKillerey** [KirilStrezikozin/BakeMaster-Blender-Addon#3]
**This feature request is:** not a duplicate

**Is your feature request related to a problem? Please describe.**
When having lots of meshes it's frustating to setup all settings for every mesh.

**Describe the solution you'd like to be implemented**
Solution could be if we get an option to change all model settings.

---

(below edited by @KirilStrezikozin)
Tasks:
- [x] Preset that affects everything
- [x] Preset for Object Settings
- [x] Preset for Source to Target 
- [x] Preset for UV Settings
- [x] Preset for Object Output Settings
- [x] Preset that affects all maps for object
- [x] Preset for Map Settings
- [x] Preset for Bake Settings

**Comment by KirilStrezikozin** [comment]
**The solution I can implement is `Panel Presets`.**
You will be able to create your own and simply choose the one to apply.

---

**Q1:**
**Option 1**: Single preset toggle for  `Object Settings`:
![image](https://user-images.githubusercontent.com/77115208/193464170-b03ed297-bf0a-4f26-b99b-689fd47108a6.png)

**Option 2**: or a separate for each subpanel:
![image](https://user-images.githubusercontent.com/77115208/193464275-90882257-4769-49ef-8c14-c96edc74bd3e.png)

**Option 3**: or Option 1 and Option 2 together:
![image](https://user-images.githubusercontent.com/77115208/193464303-c8f5150a-dba8-4a1a-bc0b-e0df93fa1399.png)

---
**Q2:**
Would it be comfortable to have a sort of `Preset Configurator`
![image](https://user-images.githubusercontent.com/77115208/193464723-463980dc-b9f9-4457-bcc3-31bc87b40598.png)
With which you could configure a preset to apply all settings for one object or all objects in the `List of Objects`

---
...
I also had a request for the `Map Presets` to quickly have added & configured maps:
![image](https://user-images.githubusercontent.com/77115208/193464443-0d0c9ddf-921e-403b-bff3-21689d65cb9c.png)

...
And I also think why not to do similar for the `Bake Settings`:
![image](https://user-images.githubusercontent.com/77115208/193464526-5a6e0b10-0bf6-4bee-9038-47714136334c.png)

**Comment by KirilStrezikozin** [comment]
@TheKillerey can you please share the option you like most for Q1 and do you agree on Q2
(you can simply reply e.g. 

> Q1: Option1, Q2: agree

 or maybe you have more comments)

**Comment by TheKillerey** [comment]
Q1: Option 3, Q2: agree

**Comment by KirilStrezikozin** [comment]
Great! I'll keep you posted on the progress.

**Comment by KirilStrezikozin** [comment]
Here is a short preview of how the bake settings presets workflow will look like. It was a bit complicated but as long as I figured out how to do it from scratch it should go faster:

https://user-images.githubusercontent.com/77115208/193620507-7a49fe41-632b-4eb2-8b32-f429f82b0c54.mp4

**Comment by KirilStrezikozin** [comment]
Tasks:
- [ ] Preset that affects everything
- [ ] Preset for Object Settings
- [ ] Preset for Source to Target 
- [ ] Preset for UV Settings
- [ ] Preset for Object Output Settings
- [ ] Preset that affects all maps for object
- [ ] Preset for Map Settings
- [ ] Preset for Bake Settings

**Comment by KirilStrezikozin** [comment]
@TheKillerey Hi, requested **_Preset System is ready_**.
My plan is to release Presets feature along with other ones I'm planning to bring to v1.5 (all list can be view [here](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/discussions/5).

---

But I'd be happy if you **_try them out now_** so I'm sure in them and can close this issue.
To do this, follow the steps below:

**1a.** Download three .py files I attached to this comment or 👇
**1b.** Clone the same three files from the [dev-bakemaster-1.0-presets branch](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/tree/build-dev-bakemaster-1.0-presets):
      [`presets.py`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/blob/build-dev-bakemaster-1.0-presets/presets.py)
      [`__init__.py`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/blob/build-dev-bakemaster-1.0-presets/__init__.py)
      [`ui_panel_base.py`](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/blob/build-dev-bakemaster-1.0-presets/ui_panel_base.py)
**2.** Go to the directory on your system where your blender addons are stored; and open `bakemaster\` folder.
**3.** replace `__init__.py` and `ui_panel_base.py` files with the downloaded `__init__.py` and `ui_panel_base.py`. And just move the downloaded `presets.py` in that folder as well.
**4.** Restart Blender and you should have Presets working.

**Comment by KirilStrezikozin** [comment]
Tell me if there's anything to change or add.

**Comment by KirilStrezikozin** [comment]
Oops, forgot to attach files)
[files4u.zip](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/files/9726932/files4u.zip)

**Comment by TheKillerey** [comment]
Heya, sorry for the delay. Everything works for me and can be pushed if needed! Thanks
