### ISSUE TITLE
BUG:Whether or not I check the "separate decimal" option, the decal will be exported as a separate image

### ISSUE THREAD

**Issue by Maiev-42** [KirilStrezikozin/BakeMaster-Blender-Addon#39]
I want to bake both the high model and the decal into the low poly, but I found that they cannot be merged and exported as one image. The decal is always a separate texture.   I have recorded screenshots of the plugin and the original files here, hoping to solve this problem。
[test.zip](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/files/12169039/test.zip)

**Comment by Maiev-42** [comment]
@KirilStrezikozin Hope you can take a look at this issue.

**Comment by KirilStrezikozin** [comment]
Hi, @chen649285912, thank you for the bug report.
Sorry for my delay in replying, I've fixed the error and you can now update BakeMasster to 2.5.1.

![image](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/assets/77115208/21a36940-5e51-4742-91bb-f48bddd652fe)

**Comment by Maiev-42** [comment]
Thank you very much!

**Comment by Maiev-42** [comment]
However, according to actual needs, we need to apply the alpha of the decal to avoid black blocks when baking the decal onto a low model.
![image](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/assets/41062473/e9650557-2d96-49b2-9473-24befaab7906)

**Comment by KirilStrezikozin** [comment]
Good point. What if turn on both Alpha and Transparent bg in BakeMaster's Format settings?
