### ISSUE TITLE
Q: Bake all doesn't bake all objects

### ISSUE THREAD

**Issue by msoo9** [KirilStrezikozin/BakeMaster-Blender-Addon#40]
Hi,
I am Meet. I am facing issue with 'Bake all' option in the bake master addon. I have around 60 objects which needs to be baked. However When I add all those objects and press bake all,  only one object get baked.

 Please provide some solution to this issue as soon as possible.

Thank You.

**Comment by KirilStrezikozin** [comment]
Hi, @msoo9. Have you added maps for each object you want to bake?

**Comment by msoo9** [comment]
Hi @KirilStrezikozin 

Thank You for your prompt response. I want to bake same map (combined) for all the objects. Once I set all the properties along with the specific map, I went for the 'bake all' option.

Do I have to specify the same map for all the objects?

**Comment by KirilStrezikozin** [comment]
Yes, you're right. With your current properties, you can click on other objects in the Objects List and see that they don't have the maps you added. You've got 2 ways to go here, depending on your specific case.

---

### Option1: Add maps to each object.
1. You can select each object in BakeMaster and add similar maps.
2. This process can be sped up using presets, you can see how [here (BakeMaster's Docs)](https://bakemaster-blender-addon.readthedocs.io/en/latest/pages/advanced/savetime.html).
i. A preset just for maps can be saved for you to quickly add all the maps you often need.
ii. Or a full object preset that can dictate all settings you see in the panel at once (address this [link](https://bakemaster-blender-addon.readthedocs.io/en/latest/pages/advanced/savetime.html#advanced-presets), it's called _Advanced Presets_). This kind of preset can be executed for all objects at once too.

### Option2: Add a container that will dictate all settings for objects inside it.
Read full explanation on containers in BakeMaster [here](https://bakemaster-blender-addon.readthedocs.io/en/latest/pages/advanced/nolimits.html#containers).
Follow links in the steps below for how-tos.

1. Enable [Name Matching](https://bakemaster-blender-addon.readthedocs.io/en/latest/pages/start/objects.html#name-matching). Note that it will automatically link matched highpolies & lowpolies into common distinct containers. You may look at _option1_ instead if that's not preferable.
2. [Create a Bake Job Group](https://bakemaster-blender-addon.readthedocs.io/en/latest/pages/advanced/nolimits.html#create-a-bake-job-group) - aka container with all objects.
3. Ensure _[Global (scroll down a bit in the doc)](https://bakemaster-blender-addon.readthedocs.io/en/latest/pages/advanced/nolimits.html#containers)_ is turned on for the container.
4. Configure uvs, bake settings, add maps.
5. Hit bake.

---

Hope this helps you.

**Comment by KirilStrezikozin** [comment]
Hi again, @msoo9. How’s your progress regarding the issue? Tell if you solved so that I can close this as completed or you need more help?

**Comment by msoo9** [comment]
Yes @KirilStrezikozin. I have solved this issue.
However If you can add the feature, selecting all objects at one click to create a Bake Job group/container will be very much useful to bake multiple objects.

Thank You for your response.

**Comment by KirilStrezikozin** [comment]
Sure, thanks.
