### ISSUE TITLE
BUG: Global presets do not include map formats

### ISSUE THREAD

**Issue by Maiev-42** [KirilStrezikozin/BakeMaster-Blender-Addon#41]
Hello,I hope global presets can include map formats.Because I often batch bake the maps of multiple objects to the specified format, but currently global presets cannot achieve this, I need to modify each object.Thank you very much!
Here is a demonstration video.

**Comment by Maiev-42** [comment]
[test.zip](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/files/12237016/test.zip)

**Comment by KirilStrezikozin** [comment]
Hi, @chen649285912. Thanks for reaching out. Have you solved this issue or the fact that it is closed is a mistake?

**Comment by KirilStrezikozin** [comment]
I will have a look at this right now.

**Comment by KirilStrezikozin** [comment]
Error exists when `Unique per map` is turned on

**Comment by KirilStrezikozin** [comment]
Found the cause: individual map properties were never actually written to a preset despite the value of `...use_unique_per_map`
