### ISSUE TITLE
Q: some map types are missing their settings

### ISSUE THREAD

**Issue by ApeOnFire** [KirilStrezikozin/BakeMaster-Blender-Addon#47]
> (Edit by @KirilStrezikozin) This is a question that was initially interpreted as a bug.

**This bug report is:**

- [x] not a duplicate

**Describe the bug**
Some map types are missing their settings and can't be configured. There may be others but this at least applies to: AO, Cavity, Curvature and Thickness.

**To Reproduce**
1. Add an Object to BM
2. Add a map and choose AO (or one of the others)
3. Check the settings that are shown

**Expected behavior**
Should be able to configure things like samples, distance, etc as shown in the docs.

**Screenshots**
Here is AO for example:
<img width="327" alt="SCR-20230928-ovfp" src="https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/assets/606495/577a39ac-c990-43c8-b7e1-0079df1f9ed8">

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: Ventura
 - Blender Version: 3.6
 - BakeMaster Version: 2.5.2

**Comment by KirilStrezikozin** [comment]
Uncheck `Default`

**Comment by ApeOnFire** [comment]
Crap - sorry 🤦‍♂️

**Comment by KirilStrezikozin** [comment]
no worries, I'll edit this issue to be a question
