### ISSUE TITLE
INSTALL ISSUE: Demo isn't working (cannot enable the addon)

### ISSUE THREAD

**Issue by Entretoize** [KirilStrezikozin/BakeMaster-Blender-Addon#61]
I downloaded the demo in added to the addon folder but when I try to activate it there's an error saying "No module named 'BakeMaster-Blender-Addon-2'.
Is there a special trick to install ??

**Comment by KirilStrezikozin** [comment]
hi, @Entretoize, where did you download the demo version from?
Try the following:
1. Unarchive the downloaded archive.
2. Rename the unarchived folder from `BakeMaster-Blender-Addon-2` to `BakeMaster`.
3. Archive the folder back.
4. Reinstall into Blender.

**Comment by Entretoize** [comment]
Forget that I finally installed the full version

**Comment by KirilStrezikozin** [comment]
Fine. I was just wondering from where you downloaded the demo version because I could mistakenly name the addon folder something else than `BakeMaster`, which won't allow Blender to enable it.

**Comment by Entretoize** [comment]
I downloaded it from the release page here

**Comment by KirilStrezikozin** [comment]
Thanks, I will keep that in mind for next releases.
