### ISSUE TITLE
BUG: Create Bake Job Group cannot proceed

### ISSUE THREAD

**Issue by Aioros2** [KirilStrezikozin/BakeMaster-Blender-Addon#78]
**This bug report is:**
- [x] duplicate
- [x] fixed

I cant create a bake job group

**Describe the bug**
i dont actually know how to succesfully bake normals after reading the doc, the first 10 attempts i thought well blender its not ready to bake normals,i kept trying and the bake was infinite time,after 30 mins i stopped it i dont know what im doing wrong after everything i went back and fix my mistake but the bake jobs keeps sending me an error

**To Reproduce**
1. Go to '...'Bake Jobs
2. Click on '....'Include High and Include Low
4. Press '...'OK
5. See error '...'

**Expected behavior**
To create a bake job

**Screenshots**
![Captura de pantalla 2024-02-27 193852](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/assets/161541541/5edc6198-12ee-46c3-80bd-286309e89cfb)

**Desktop (please complete the following information):**
 -
![image](https://github.com/KirilStrezikozin/BakeMaster-Blender-Addon/assets/161541541/66f72069-fd40-490a-9b83-e719f022b39d)

 - Blender Version [e.g. Blender 3.2.2]
 - 4.0.0
 - BakeMaster Version [e.g. 1.0]
 -2.6.0 

**Additional context**

**Comment by KirilStrezikozin** [comment]
@Aioros2, please update BakeMaster (from BlenderMarket/Gumroad) to its latest version - `2.6.1`. The bug appearing when creating a bake job group comes from `2.6.0` and was already fixed in the newest version.

**Comment by KirilStrezikozin** [comment]
> i dont actually know how to succesfully bake normals after reading the doc, the first 10 attempts i thought well blender its not ready to bake normals,i kept trying and the bake was infinite time

When the bake goes on for infinity (the sign it's like that is when BakeMaster says `Baking ...: map ..., x of total` but you don't see any bake percentage progress displayed). In such a case, hit `BACKSPACE` on your keyboard to cancel the bake. Then rerun the bake. If you still experience the problem, restart blender.

**Comment by KirilStrezikozin** [comment]
I'm closing this as of now, as the original bug was resolved. Feel free to leave comments. Don't hesitate to ask anything about working with BakeMaster on our discord.
